backend:
  name: git-gateway
  branch: feature/netlify-cms
  site_url: https://infallible-fermat-91477a.netlify.com/

display_url: https://infallible-fermat-91477a.netlify.com/

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: static/content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
