backend:
  name: git-gateway
  branch: feature/netlify-cms
  site_url: https://infallible-fermat-91477a.netlify.com/

display_url: https://infallible-fermat-91477a.netlify.com/

media_folder: 'static/images'
public_folder: 'images'

collections:
  - name: 'team' # Used in routes, e.g., /admin/collections/blog
    label: 'Team' # Used in the UI
    folder: 'posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: name
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'team-post',
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Profession', name: 'profession', widget: 'string' }
      - { label: 'Profile Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
