backend:
  name: git-gateway
  branch: feature/netlify-cms

publish_mode: editorial_workflow

media_folder: static/img

collections:
  - name: blog
    label: Blog
    folder: static/content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
